#!/bin/bash

mariadb service start

sleep 3

mariadb -u root << EOF

CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE}

USE ${MYSQL_DATABASE}

CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY ${MYSQL_PASSWORD}

GRANT ALL PRIVELEGES ON '${MYSQL_DATABASE}.*' TO '${MYSQL_USER}'@'%'

ALTER USER 'root'@'localhost' IDENTIFIED BY ${MYSQL_ROOT_PASSWORD}

FLUSH PRIVELEGES

EOF

mysqladmin -u root -p${MYSQL_ROOT_PASSWORD} shutdown

exec mysqld_safe